### PR TITLE
Add default templates for Tekton org projects.

### PR DESCRIPTION
**Pull request by wlynch**
Full list of available files / options listed here:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file

Most templates taken from pipeline repo, trimmed of any
pipeline-specific instructions.

### CODE REVIEW

**Comment by bobcatfish** [comment]
Thanks for putting this together @wlynch !

I don't see any reason not to merge this so I'm gonna hit the merge button - @vdemeester @afrittoli @abayer @ImJasonH please follow up if we want to change anything.

**Comment by bobcatfish** [comment]
And then right after I hit merge I realized:

@wlynch I think we want some of these files outside of .github? e.g. in our other repos we have CONTRIBUTING.md, code-of-conduct.md in the top level folder 🤔

**Comment by wlynch** [comment]
Should be fine. These are defaults. From the [docs](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file):

> For example, anyone who creates an issue or pull request in a public repository that does not have its own CONTRIBUTING file will see a link to the default CONTRIBUTING file. If a repository has any files in its own .github/ISSUE_TEMPLATE folder, including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.

**Comment by bobcatfish** [comment]
> GitHub will use and display default files for any public repository owned by the account that does not have its own file of that type in any of the following places:

> the root of the repository
> the .github folder
> the docs folder

Ah I guess GitHub supports keeping these known files in any of the above locations

**Pull request merged**
