### PR TITLE
Profile README for the tektoncd org landing page

### PR DESCRIPTION
**Pull request by afrittoli**
Add a simple README.md to display a profile in the org landing page.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester @bobcatfish @dibyom @abayer

**Comment by bobcatfish** [comment]
thanks @afrittoli ! we can always add more detail later if we want, this seems like a good starting point :D

/approve

**Comment by dibyom** [comment]
(Looks like we have to manually merge this PR?)

**Pull request merged**
