### PR TITLE
Adding tektoncd wide default SECURITY.md

### PR DESCRIPTION
**Pull request by afrittoli**
Add a default SECURITY.md with instruction regarding how to report
security issues safely.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

### CODE REVIEW

**Comment by bobcatfish** [comment]
Thanks @afrittoli looks great to me. 3 working days feels like a reasonable timeline - i assume that between all of us we can make sure someone is always available. i wonder if we want to do a bit more coordination to make sure that's the case, just in case we all go on holidays at once or something? (or maybe the build captain can be part of it somehow 🤔 )

**Comment by dlorenc** [comment]
Note that you don't need to restrict the vulnerability management/reporting to just the governing board. It should be a relatively small list of people from different organizations, but feel free to solicit help from others.

I'd be happy to help out here, for example :)

**Comment by afrittoli** [comment]
> Note that you don't need to restrict the vulnerability management/reporting to just the governing board. It should be a relatively small list of people from different organizations, but feel free to solicit help from others.
> 
> I'd be happy to help out here, for example :)

Thanks @dlorenc 🎉 

This wasn't meant to be restricted to the GB members, it was just an initial list to get started.
I'll add you to the DL.

**Comment by afrittoli** [comment]
> Thanks @afrittoli looks great to me. 3 working days feels like a reasonable timeline - i assume that between all of us we can make sure someone is always available. i wonder if we want to do a bit more coordination to make sure that's the case, just in case we all go on holidays at once or something? (or maybe the build captain can be part of it somehow 🤔 )

@bobcatfish That's a good point. I think the most important part of this is to let people know how to report vulnerabilities, perhaps we don't need to commit to the 3 days; I think the wording allows for a "we're looking into this" kind of reply still, that could be used in case 3 days are not enough to decide whether an issue is considered a security vulnerability by the Tekton SVM team. 

+1 we'll need some way to coordinate. I'd suggest we can use the DL to let other know if someone is looking into an issue or to ask for help. GithHub provides tooling to discuss and work on private patches which is a great help: https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories

**Pull request merged**
